version: '3.8'

services:
  keyvideo-backend:
    build: .
    container_name: keyvideo-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
