export const SCENE_PROMPT_DESCRIPTIONS: Record<string, string> = {
  street: 'posing in a premium cinematic urban street corner. The background features a consistent architectural facade with sleek dark metal panels, a large polished display window reflecting warm golden indoor lights on the left, and clean wet asphalt pavement reflecting soft ambient streetlights. Background city traffic is softly blurred into beautiful bokeh (out-of-focus circle lights), creating depth while maintaining a consistent outdoor urban layout.',
  studio: 'posing in a professional high-end wabi-sabi photo studio. The background features a textured beige micro-cement wall, a large geometric concrete archway on the left, and a soft sunlight beam slanting from a high side window creating elegant shadows. On the right side, there is a minimalist travertine stone pedestal and a designer lounge chair, maintaining a consistent minimalist studio setting with high-end gallery layout.',
  home: 'posing in a modernist luxury villa interior. The setting consists of polished micro-cement floors, a premium warm travertine marble accent wall in the background, and a large floor-to-ceiling glass window on the right showcasing a softly blurred outdoor garden with lush misty green foliage. The scene features warm ambient lighting from minimalist recessed led strips, maintaining a highly consistent, premium indoor layout.',
  office: 'posing in a sleek modern executive office interior. The background features a large transparent glass curtain wall showcasing a distant blurred skyline of skyscrapers at twilight, polished light-gray terrazzo flooring reflecting soft overhead lights, and a luxury dark walnut wood panel wall on the left. The scene maintains a consistent high-end corporate layout.',
  beach: 'posing at a high-end luxury resort private beach. The setting features clean fine white sand, a minimalist white concrete colonnade and arch structure in the background on the left, and palm leaf shadows cast onto a light-colored stucco wall. In the distance, a calm turquoise ocean with shimmering sunlight bokeh is visible under a warm morning sky, maintaining a consistent tropical resort layout.',
  runway: 'posing on a high-fashion runway stage. The background features a raw textured fair-faced concrete wall, a dark reflective mirror-like catwalk stage floor reflecting high-contrast overhead spotlights, and a subtle soft mist in the ambient air. Spotlights create dramatic light-and-shadow outlines on the model, maintaining a consistent runway environment.',
  minimalist: 'posing against a minimalist gallery concrete wall. The background features a textured beige plaster wall with clean geometric recessed niches, soft artistic shadows, and a gentle slanting warm light beam from the top left. The space is uncluttered with elegant architectural minimalism and generous negative space, maintaining a consistent high-end brand lookbook setting.'
};
